// AUTOGENERATED SEED DATA WITH COORDINATES
export const POP_SEED_DATA = [
  {
    "id": "1",
    "asset_code": "POP_1BAU10001_TK4 SULAA BAUBAU ODC",
    "name": "POP_1BAU10001_TK4 SULAA BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598596\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.49879,
    "longitude": 122.563
  },
  {
    "id": "2",
    "asset_code": "POP_1BAU10002_TK4 WOLIO BAUBAU ODC",
    "name": "POP_1BAU10002_TK4 WOLIO BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598641\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.46356,
    "longitude": 122.607
  },
  {
    "id": "3",
    "asset_code": "POP_1BAU10003_BUKIT WOLIO INDAH MINI POP",
    "name": "POP_1BAU10003_BUKIT WOLIO INDAH MINI POP",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598633\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.47067,
    "longitude": 122.622
  },
  {
    "id": "4",
    "asset_code": "POP_1BAU10004_TK4 KATOBENGKE BAUBAU ODC",
    "name": "POP_1BAU10004_TK4 KATOBENGKE BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598588\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.47245,
    "longitude": 122.585
  },
  {
    "id": "5",
    "asset_code": "POP_1BAU10005_TK4 BATARAGURU BAUBAU ODC",
    "name": "POP_1BAU10005_TK4 BATARAGURU BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598633\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.46366,
    "longitude": 122.622
  },
  {
    "id": "6",
    "asset_code": "POP_1BAU10006_TK4 WAJO BAUBAU ODC",
    "name": "POP_1BAU10006_TK4 WAJO BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598674\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.45798,
    "longitude": 122.599
  },
  {
    "id": "7",
    "asset_code": "POP_1KDI10001_BTN PNS KOTA 1/KENDARI GI SHELTER 1 OLT",
    "name": "POP_1KDI10001_BTN PNS KOTA 1/KENDARI GI SHELTER 1 OLT",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201259749\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"- -\"}",
    "latitude": -4.02821,
    "longitude": 122.474
  },
  {
    "id": "8",
    "asset_code": "POP_1KDI10002_PERDOS KENDARI 1//KENDARI GI SHELTER 2 OLT",
    "name": "POP_1KDI10002_PERDOS KENDARI 1//KENDARI GI SHELTER 2 OLT",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201743640\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"- -\"}",
    "latitude": -4.0104,
    "longitude": 122.529
  },
  {
    "id": "9",
    "asset_code": "POP_1KDI10004_TK4 WATULONDO KENDARI ODC",
    "name": "POP_1KDI10004_TK4 WATULONDO KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201916583\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.97674,
    "longitude": 122.487
  },
  {
    "id": "10",
    "asset_code": "POP_1KDI10005_TK4 LALODATI KENDARI ODC",
    "name": "POP_1KDI10005_TK4 LALODATI KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300828335\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.95833,
    "longitude": 122.5
  },
  {
    "id": "11",
    "asset_code": "POP_1KDI10006_TK4 LAHUNDAPE KENDARI ODC",
    "name": "POP_1KDI10006_TK4 LAHUNDAPE KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300828343\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.9634,
    "longitude": 122.531
  },
  {
    "id": "12",
    "asset_code": "POP_1KDI10007_TK4 WAMOMBALATA KENDARI ODC",
    "name": "POP_1KDI10007_TK4 WAMOMBALATA KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300828766\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.94678,
    "longitude": 122.51
  },
  {
    "id": "13",
    "asset_code": "POP_1KDI10008_TK4 KAMBU KENDARI ODC",
    "name": "POP_1KDI10008_TK4 KAMBU KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.01016,
    "longitude": 122.54
  },
  {
    "id": "14",
    "asset_code": "POP_1KDI10009_TK4 DAPU DAPURA KENDARI ODC",
    "name": "POP_1KDI10009_TK4 DAPU DAPURA KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300829991\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.96921,
    "longitude": 122.565
  },
  {
    "id": "15",
    "asset_code": "POP_1KDI10010_KANTOR GUBERNUR SULAWESI TENGGARA ODC",
    "name": "POP_1KDI10010_KANTOR GUBERNUR SULAWESI TENGGARA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201915997\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"- -\"}",
    "latitude": -4.03094,
    "longitude": 122.541
  },
  {
    "id": "16",
    "asset_code": "POP_1KDI10012_MANDONGA MINI POP",
    "name": "POP_1KDI10012_MANDONGA MINI POP",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201926239\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.96008,
    "longitude": 122.523
  },
  {
    "id": "17",
    "asset_code": "POP_1KDI10013_CB SMAN 2 KENDARI ODC",
    "name": "POP_1KDI10013_CB SMAN 2 KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201916886\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"- -\"}",
    "latitude": -4.00384,
    "longitude": 122.558
  },
  {
    "id": "18",
    "asset_code": "POP_1KDI10015_TK4 ABELI KENDARI ODC",
    "name": "POP_1KDI10015_TK4 ABELI KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201984923\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.99154,
    "longitude": 122.585
  },
  {
    "id": "19",
    "asset_code": "POP_1KDI10016_TK4 MATABUBU KENDARI ODC",
    "name": "POP_1KDI10016_TK4 MATABUBU KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201983912\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.00298,
    "longitude": 122.568
  },
  {
    "id": "20",
    "asset_code": "POP_1KDI10017_TK4 WUA WUA KENDARI ODC",
    "name": "POP_1KDI10017_TK4 WUA WUA KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201984907\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.99874,
    "longitude": 122.49
  },
  {
    "id": "21",
    "asset_code": "POP_1KDI10018_TK4 LEPO LEPO KENDARI ODC",
    "name": "POP_1KDI10018_TK4 LEPO LEPO KENDARI ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201984931\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.02326,
    "longitude": 122.511
  },
  {
    "id": "22",
    "asset_code": "POP_1KDI10019_HOMBIS MINI POP",
    "name": "POP_1KDI10019_HOMBIS MINI POP",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201795106\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.0273,
    "longitude": 122.491
  },
  {
    "id": "23",
    "asset_code": "POP_1KDI10022_BTN1 MINI POP",
    "name": "POP_1KDI10022_BTN1 MINI POP",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201836470\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.98558,
    "longitude": 122.515
  },
  {
    "id": "24",
    "asset_code": "POP_1KKA10002_TK4 LAMOKATO KOLAKA ODC",
    "name": "POP_1KKA10002_TK4 LAMOKATO KOLAKA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800572153\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.05379,
    "longitude": 121.598
  },
  {
    "id": "25",
    "asset_code": "POP_1KKA10003_TK4 TAHOA KOLAKA ODC",
    "name": "POP_1KKA10003_TK4 TAHOA KOLAKA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800572216\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.07892,
    "longitude": 121.635
  },
  {
    "id": "26",
    "asset_code": "POP_1KKA10004_TK4 KOLAKAASHI KOLAKA ODC",
    "name": "POP_1KKA10004_TK4 KOLAKAASHI KOLAKA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800572146\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.066,
    "longitude": 121.614
  },
  {
    "id": "27",
    "asset_code": "POP_1KKA10005_TK4 KOWIOHA KOLAKA ODC",
    "name": "POP_1KKA10005_TK4 KOWIOHA KOLAKA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800572208\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.11231,
    "longitude": 121.677
  },
  {
    "id": "28",
    "asset_code": "POP_1PSW10001_TK4 PASAR WAJO BAUBAU ODC",
    "name": "POP_1PSW10001_TK4 PASAR WAJO BAUBAU ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328501020829\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.49663,
    "longitude": 122.843
  },
  {
    "id": "29",
    "asset_code": "POP_1RAH10001_TK4 RAHA II MUNA ODC",
    "name": "POP_1RAH10001_TK4 RAHA II MUNA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328200619580\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.83056,
    "longitude": 122.721
  },
  {
    "id": "30",
    "asset_code": "POP_1RAH10002_TK4 RAHA I MUNA ODC",
    "name": "POP_1RAH10002_TK4 RAHA I MUNA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328200619580\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.83056,
    "longitude": 122.721
  },
  {
    "id": "31",
    "asset_code": "POP_1RMB10001_TK4 LAMERORO BOMBANA ODC",
    "name": "POP_1RMB10001_TK4 LAMERORO BOMBANA ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323400312650\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.77688,
    "longitude": 122.053
  },
  {
    "id": "32",
    "asset_code": "POP_1UNH10001_TK4 WAWOTOBI KONAWE ODC",
    "name": "POP_1UNH10001_TK4 WAWOTOBI KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600530901\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.86852,
    "longitude": 122.113
  },
  {
    "id": "33",
    "asset_code": "POP_1UNH10002_TK4 RAWANGA KONAWE ODC",
    "name": "POP_1UNH10002_TK4 RAWANGA KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600530897\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.89764,
    "longitude": 122.103
  },
  {
    "id": "34",
    "asset_code": "POP_1UNH10003_TK4 SENDANG MULYASARI KONAWE ODC",
    "name": "POP_1UNH10003_TK4 SENDANG MULYASARI KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600532341\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.85159,
    "longitude": 122.072
  },
  {
    "id": "35",
    "asset_code": "POP_1UNH10004_TK4 PUUNAHA KONAWE ODC",
    "name": "POP_1UNH10004_TK4 PUUNAHA KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600532366\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.86788,
    "longitude": 122.066
  },
  {
    "id": "36",
    "asset_code": "POP_1UNH10005_TK4 TUMPAS KONAWE ODC",
    "name": "POP_1UNH10005_TK4 TUMPAS KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600532358\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.8603,
    "longitude": 122.046
  },
  {
    "id": "37",
    "asset_code": "POP_1UNH10006_TK4 ANGGOPIU KONAWE ODC",
    "name": "POP_1UNH10006_TK4 ANGGOPIU KONAWE ODC",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600532374\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.89288,
    "longitude": 122.041
  },
  {
    "id": "38",
    "asset_code": "TK 4_RSUL_Kota Baubau_Murhum",
    "name": "TK 4_RSUL_Kota Baubau_Murhum",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598570\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.467256,
    "longitude": 122.598108
  },
  {
    "id": "39",
    "asset_code": "OLT Puuwatu",
    "name": "OLT Puuwatu",
    "category": "POP-A",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201916583\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.97674,
    "longitude": 122.487
  },
  {
    "id": "40",
    "asset_code": "POP_1KDI001_KENDARI AREA PLN",
    "name": "POP_1KDI001_KENDARI AREA PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"5.500\",\"daya\":\"1\",\"phasa\":\"Phasa Vertiv\",\"rectifier_brand\":\"1 Phasa\"}",
    "latitude": -3.99628,
    "longitude": 122.499
  },
  {
    "id": "41",
    "asset_code": "POP_1KDI10000_KENDARI GI SHELTER PLN",
    "name": "POP_1KDI10000_KENDARI GI SHELTER PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201648756\",\"daya\":\"10.600\",\"phasa\":\"3 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -4.02441,
    "longitude": 122.466
  },
  {
    "id": "42",
    "asset_code": "POP_1KKA10000_KOLAKA GI SHELTER PLN",
    "name": "POP_1KKA10000_KOLAKA GI SHELTER PLN",
    "category": "POP-B",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800490486\",\"daya\":\"10.600\",\"phasa\":\"3 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -4.07298,
    "longitude": 121.637
  },
  {
    "id": "43",
    "asset_code": "POP_1LSS10000_LASUSUA GI SHELTER PLN",
    "name": "POP_1LSS10000_LASUSUA GI SHELTER PLN",
    "category": "POP-B",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323500231001\",\"daya\":\"10.600\",\"phasa\":\"3 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -3.53668,
    "longitude": 120.918
  },
  {
    "id": "44",
    "asset_code": "POP_1UNH10000_UNAAHA GI SHELTER PLN",
    "name": "POP_1UNH10000_UNAAHA GI SHELTER PLN",
    "category": "POP-B",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600465617\",\"daya\":\"10.600\",\"phasa\":\"3 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -3.86181,
    "longitude": 122.074
  },
  {
    "id": "45",
    "asset_code": "POP_1ADL10000_ANDOOLO GI PLN",
    "name": "POP_1ADL10000_ANDOOLO GI PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"\",\"daya\":\"\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -4.34953,
    "longitude": 122.245
  },
  {
    "id": "46",
    "asset_code": "POP_1BAU10000_BAUBAU PLTD PLC PLN",
    "name": "POP_1BAU10000_BAUBAU PLTD PLC PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328101598674\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.45789,
    "longitude": 122.598
  },
  {
    "id": "47",
    "asset_code": "POP_1BGK10000_BAHODOPI MINI POP",
    "name": "POP_1BGK10000_BAHODOPI MINI POP",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"312110458582\",\"daya\":\"1.600\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ALPHA\"}",
    "latitude": -2.79621,
    "longitude": 122.122
  },
  {
    "id": "48",
    "asset_code": "POP_1KDI002_KENDARI AREA MINI POP",
    "name": "POP_1KDI002_KENDARI AREA MINI POP",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201902449\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"EMERSON\"}",
    "latitude": -3.99622,
    "longitude": 122.5
  },
  {
    "id": "49",
    "asset_code": "POP_1KDI10003_BENU BENUA ULP MINI POP PLN",
    "name": "POP_1KDI10003_BENU BENUA ULP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300798483\",\"daya\":\"5.500\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENETEK\"}",
    "latitude": -3.96651,
    "longitude": 122.562
  },
  {
    "id": "50",
    "asset_code": "POP_1KDI10014_PUUWATU GI SHELTER PLN",
    "name": "POP_1KDI10014_PUUWATU GI SHELTER PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201907951\",\"daya\":\"23.000\",\"phasa\":\"3 Phasa\",\"rectifier_brand\":\"SMART PACK 10\"}",
    "latitude": -3.95591,
    "longitude": 122.506
  },
  {
    "id": "51",
    "asset_code": "POP_1KDI10020_ALMIRA MINI POP",
    "name": "POP_1KDI10020_ALMIRA MINI POP",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201812196\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -4.00224,
    "longitude": 122.503
  },
  {
    "id": "52",
    "asset_code": "POP_1KDI10021_DAMKAR MINI POP",
    "name": "POP_1KDI10021_DAMKAR MINI POP",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201836462\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -3.97624,
    "longitude": 122.508
  },
  {
    "id": "53",
    "asset_code": "POP_1KDI10023_LAPULU KP MINI POP PLN",
    "name": "POP_1KDI10023_LAPULU KP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323201902431\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"SMART PACK 10\"}",
    "latitude": -3.98388,
    "longitude": 122.581
  },
  {
    "id": "54",
    "asset_code": "POP_1KKA001_WOLO KP MINI POP PLN",
    "name": "POP_1KKA001_WOLO KP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -3.83489,
    "longitude": 121.268
  },
  {
    "id": "55",
    "asset_code": "POP_1KKA002_KOLAKA PLTD MINI POP PLN",
    "name": "POP_1KKA002_KOLAKA PLTD MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323800562338\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -4.06705,
    "longitude": 121.621
  },
  {
    "id": "56",
    "asset_code": "POP_1KKA003_RATE-RATE KP MIKRO POP PLN",
    "name": "POP_1KKA003_RATE-RATE KP MIKRO POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600412943\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"PSU\"}",
    "latitude": -4.04878,
    "longitude": 121.89
  },
  {
    "id": "57",
    "asset_code": "POP_1LSS001_OLO-OLOHO KP MINI POP PLN",
    "name": "POP_1LSS001_OLO-OLOHO KP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323500209795\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -3.22137,
    "longitude": 121.049
  },
  {
    "id": "58",
    "asset_code": "POP_1LSS002_KOLAKA UTARA ULP MINI POP PLN",
    "name": "POP_1LSS002_KOLAKA UTARA ULP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"32350020987\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"SMART PACK 10\"}",
    "latitude": -3.5237,
    "longitude": 120.912
  },
  {
    "id": "59",
    "asset_code": "POP_1LSS003_RANTEANGIN KP MINI POP PLN",
    "name": "POP_1LSS003_RANTEANGIN KP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323500209779\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -3.67815,
    "longitude": 121.022
  },
  {
    "id": "60",
    "asset_code": "POP_1PSW10000_PASARWAJO ULP MINI POP PLN",
    "name": "POP_1PSW10000_PASARWAJO ULP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328501020829\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": -5.49658,
    "longitude": 122.843
  },
  {
    "id": "61",
    "asset_code": "POP_1RAH10000_RAHA KP PLC PLN",
    "name": "POP_1RAH10000_RAHA KP PLC PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"328200619580\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"Huawei\"}",
    "latitude": 4.83043,
    "longitude": 122.721
  },
  {
    "id": "62",
    "asset_code": "POP_1RMB10000_KASIPUTE GI PLC PLN",
    "name": "POP_1RMB10000_KASIPUTE GI PLC PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"\",\"daya\":\"\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -4.73201,
    "longitude": 122.025
  },
  {
    "id": "63",
    "asset_code": "POP_1UNH001_LAMBUYA PLTD MIKRO POP PLN",
    "name": "POP_1UNH001_LAMBUYA PLTD MIKRO POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600412935\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"PSU\"}",
    "latitude": -3.97001,
    "longitude": 122.067
  },
  {
    "id": "64",
    "asset_code": "POP_1UNH002_UNAAHA ULP MIKRO POP PLN",
    "name": "POP_1UNH002_UNAAHA ULP MIKRO POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323600412950\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"PSU\"}",
    "latitude": -3.8605,
    "longitude": 122.046
  },
  {
    "id": "65",
    "asset_code": "POP_1WGD10000_ASERA KP MINI POP PLN",
    "name": "POP_1WGD10000_ASERA KP MINI POP PLN",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300747253\",\"daya\":\"4.400\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"ENATEL\"}",
    "latitude": -3.50873,
    "longitude": 122.105
  },
  {
    "id": "66",
    "asset_code": "POP_1WGD10001_TETEWATOE MIKRO POP",
    "name": "POP_1WGD10001_TETEWATOE MIKRO POP",
    "category": "POP-D",
    "location": "KENDARI",
    "specifications": "{\"id_pln\":\"323300799286\",\"daya\":\"1.300\",\"phasa\":\"1 Phasa\",\"rectifier_brand\":\"SMART PACK 9\"}",
    "latitude": -3.16291,
    "longitude": 122.115
  },
];
